---
# group variables for vr-vmx platform

ansible_connection: ansible.netcommon.network_cli
ansible_network_os: junipernetworks.junos.junos
  #ansible_ssh_user: admin

#ansible_connection=ansible.netcommon.network_cli
#ansible_network_os=junipernetworks.junos.junos
#ansible_user=admin

ansible_ssh_private_key_file: /home/anton/.ssh/id_rsa



