---
- name: Load and commit base configuration
  hosts: vr-vmx
  gather_facts: false
  connection: local

  roles:
    - Juniper.junos
  tasks:
    - name: Load configuration from a local file and commit
      juniper_junos_config:
        load: merge
        format: set
        src: "./configuration/sshRSA.txt"
      register: response
      register: response

    - name: Print the response
      debug:
        var: response
