---
- name: Deploy containerlab topology
  hosts: localhost
  gather_facts: false
  become: true
  vars_prompt:
    - name: ansible_become_password
      prompt: "Enter the sudo password"
      private: yes

  tasks:
    - name: Run clab deploy command
      ansible.builtin.shell: "sudo -S clab deploy -t /home/anton/git_hub/ansible-juniper-lab-mpls-l2vpn-public/clab/topology.yml"
      environment:
        SUDO_PASS: "{{ ansible_become_password }}"
          #no_log: true

    - name: Wait for the deployment to complete
      pause:
        minutes: 3

    - name: Check Docker containers status
      ansible.builtin.shell: "docker ps -a"
      register: docker_ps_output

    - name: Check for healthy status
      ansible.builtin.debug:
        msg: "All containers are healthy"
      when: "'(healthy)' in docker_ps_output.stdout"

